import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const googleAuth = () => { 
    const google_auth_link = process.env.REACT_APP_GOOGLE_AUTH_URL
    console.log(google_auth_link)
    window.location.href = `${process.env.REACT_APP_GOOGLE_AUTH_URL}`;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to Echo Lounge</h1>
        <button onClick={googleAuth}>Try Me</button>
      </main>
    </div>
  )
}
