import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logoStyles from "../styles/Logo.module.css"

export default function Home() {
	const googleAuth = async () => { 
		window.location.href="http://localhost:8080/api/auth/google/authenticate"
	}

  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
            <nav className= "navbar" style={{"backgroundColor": "blue"}}>
                <div className="container-fluid">
                    <h1 className={`${logoStyles.font}`}>
                        <svg xmlns="http://www.w3.org/2000/svg" width="5%" height="5%" fill="currentColor" className="bi bi-collection-play-fill m-3" viewBox="0 0 16 16">
                            <path d="M2.5 3.5a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1zm2-2a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1zM0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6zm6.258-6.437a.5.5 0 0 1 .507.013l4 2.5a.5.5 0 0 1 0 .848l-4 2.5A.5.5 0 0 1 6 12V7a.5.5 0 0 1 .258-.437"/>
                        </svg>
                        ECHO LOUNGE
                    </h1>
                </div>
            </nav>
        </header>

        <div className={styles.container}>
            <div className={styles.info}>
                <div >
                    <h1 className={styles.title}>SHARE YOUR FAVORITE VIDEOS WITH YOUR FRIENDS LOVED ONES!</h1>
                </div>
                <div>
                    <p className={styles.description}>
                        Watch, sync, and share unforgettable video moments together in real time
                    </p>
                </div>
                <div>
                    <button className={styles.button}
                        onClick={googleAuth}>Lets Begin
                    </button>
                </div>
                </div>
                <div className={styles.picture}>
                    <h1>Picture </h1>
                </div>
        </div>

    </div>


  )
}
